// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrvupouxxqqtgvfzfegv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydnVwb3V4eHFxdGd2ZnpmZWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTM5MjQsImV4cCI6MjA2NDU2OTkyNH0.s45f7t2O7USBVz-8hi3RP2SczOlEcsb1AqXH3baDf0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);